### PR TITLE
[WIP] dict key using Py3 str not bytes in milestones_fulfillment_paths

### PR DESCRIPTION
**Pull request by terapyon**
- [x] I will send contributor-agreement.pdf
- [ ] Just got coverage html error

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @terapyon! I've created [OSPR-3381](https://openedx.atlassian.net/browse/OSPR-3381) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @terapyon! I've created [OSPR-3521](https://openedx.atlassian.net/browse/OSPR-3521) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@terapyon Have you had a chance to sign our contributor agreement? Once it is done, we will be able to review your code going forward. Thanks!

**Comment by terapyon** [comment]
I'm sorry I will soon send CLA.

**Comment by feanil** [comment]
@terapyon any update?  I ended up doing this work on a different branch because I did not see that you had already made this change but I'm happy to land this and then make my changes on top of it.

**Comment by terapyon** [comment]
@feanil I'm sorry. I could not make a time. Please marge or something.

**Comment by terapyon** [comment]
@natabene I already sent CLA. Did you get my CLA?

**Comment by natabene** [comment]
@terapyon Thank you very much for signing and sending. Please give our legal team a few days to process it. Once they are done, they will reach out to you and us, confirming that you are all set and your code can be reviewed.

**Comment by feanil** [comment]
@terapyon I apologize, the fault is mine for not checking to see if you had already done the work.  I'll try not to make this mistake again.    In the case of this PR, I'm going to merge my alternative since it has other conversion related changes as well.

**Comment by edx-webhook** [comment]
@terapyon Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-milestones&entry.867055334=https://github.com/edx/edx-milestones/pull/33&entry.1484655318=https://github.com/terapyon&entry.752974735=2019-05-06+21:24&entry.1917517419=2019-06-06+14:39&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
