### PR TITLE
INCR-21: making tests pass with python3

### PR DESCRIPTION
**Pull request by annagav**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @annagav! I've created [OSPR-3028](https://openedx.atlassian.net/browse/OSPR-3028) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@annagav Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions.

**Comment by pdpinch** [comment]
Looks like there's a small linting error + it's having trouble importing `builtins` ??

**Comment by pdpinch** [comment]
@natabene Anna is an employee of MIT Open Learning. I think her contributions should be covered by the MIT agreement.

**Comment by natabene** [comment]
@pdpinch  Thanks, Peter. @annagav I have added you to our contributors list, so going on forward we can review your code. Please let me know once it is ready to be reviewed.

**Comment by jmbowman** [comment]
Instead of switching directly from `unicode` to `str`, should probably switch to `six.text_type` instead in order to work with both Python 2 and 3.  The `python-modernize` utility from the `modernize` package should help with things like that automatically; the pending [update to OEP-7](https://github.com/edx/open-edx-proposals/blob/dd6820fd81a2a7b32ede9ad05bfa858c523d1b6c/oeps/oep-0007-bp-migrate-to-python3.rst) tries to make that a little more clear.

**Comment by edx-webhook** [comment]
@annagav Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-milestones&entry.867055334=https://github.com/edx/edx-milestones/pull/32&entry.1484655318=https://github.com/annagav&entry.752974735=2019-01-30+20:46&entry.1917517419=2019-02-26+16:38&entry.2133058324=No) so we can improve your experience in the future.

**Comment by annagav** [comment]
Closed by accident

**Comment by estute** [comment]
@annagav can you add the python3.6 tox environment to the travis.yml file?

**Comment by jmbowman** [comment]
Down to just 2 failing tests!  @annagav , do you want to try fixing those or should we wrap up this ticket here and create a new one for that?  Honestly this task was too big for an INCR ticket, we've learned how to split them up better since this was created.  We could review and merge the changes made so far by telling Travis it's ok for the Python 3.6 tests to fail for now, like this: https://github.com/edx/xblock-sdk/blob/master/.travis.yml#L22-L23

**Comment by edx-webhook** [comment]
@annagav 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-milestones&entry.867055334=https://github.com/edx/edx-milestones/pull/32&entry.1484655318=https://github.com/annagav&entry.752974735=2019-01-30+20:46&entry.1917517419=2019-04-09+21:56&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
